import "../styles/globals.css";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { AppPropsWithLayout } from "../utils/types";
import Loader from "../components/common/Loader";
import { LanguageProvider } from "../utils/translater/LanguageContext";

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const [loading, setLoading] = useState<boolean>(true);
  const getLayout = Component.getLayout ?? ((page) => page);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);

  return (
    <div>
      <Head>
        <title>Lorix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LanguageProvider>
        {loading ? <Loader /> : getLayout(<Component {...pageProps} />)}
      </LanguageProvider>
    </div>
  );
}
